version: '3'
services: 

  app:
    build: .
    ports:
      - 5000:5000
    environment:       
      FLASK_ENV: development
      FLASK_APP: app.py

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account
      MYSQL_USER: galeria
      MYSQL_PASSWORD: galeria
    ports:
      - 3306:3306
